### PR TITLE
Adds png pattern opacity support

### PR DESCRIPTION
**Pull request by BenjaminVanRyseghem**
Add the options to have a background color, with a semi-transparent pattern on top, as discussed in #16

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
https://www.youtube.com/watch?v=aHN6AViJAvI

?

**Comment by TorsteinHonsi** [comment]
The diff in https://github.com/foretagsplatsen/pattern-fill/commit/d29034840a71d9a592b61b7965dc452b4aefb48c is too great to merge. It seems like you changed the line endings or something, because all lines are changed.

**Comment by BenjaminVanRyseghem** [comment]
I accidentally replace spaces with tabs. Let me try to fix it ;)

**Comment by BenjaminVanRyseghem** [comment]
I cleaned it up :smile: 

Sorry again :wink:

**Comment by TorsteinHonsi** [comment]
There's still a lot of non-related changes here...
https://github.com/foretagsplatsen/pattern-fill/commit/5cafff34b30d087825e2fb5ac57fe9f18e201b1a

**Comment by BenjaminVanRyseghem** [comment]
See #18 for a clean version

**Pull request closed without merging**
