### PR TITLE
Including "backgroundColor" and "patternTransform" to options

### PR DESCRIPTION
**Pull request by rafael-trevisan**
Some small modifications to support polka dot pattern

### CODE REVIEW

**Comment by rafael-trevisan** [comment]
Here is an example of what I needed:

```
    "defs": {
      "patterns": [
        {
          "id": "circle-2a",
          "width": 3,
          "height": 3,
          "backgroundColor": "#6bcff6",
          "patternTransform": "rotate(45)",
          "path": {
            "d": "M 1, 1 m -0.75, 0 a 0.75,0.75 0 1,0 1.50,0 a 0.75,0.75 0 1,0 -1.50,0",
            "fill": "#9d070d"
          }
        }
      ]
    }
```
and here is the exported png with these changes:
test

**Comment by IgorFIE** [comment]
Is this merge possible? I actually need patternTransform since I want to scale/rotate a pattern, or is there another way of doing it in highcharts?

**Comment by pawelfus** [comment]
Hi @IgorFIE 

This plugin is no longer maintained, see [Deprecation notice](https://github.com/highcharts/pattern-fill#deprecation-notice).

**Comment by IgorFIE** [comment]
Thanks @pawelfus

**Pull request closed without merging**
